
service: serverless-2024-prova
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::637423409147:role/LabRole
  
  environment:
    DB_HOST: db-afp-2024.c7ky6o82a8hh.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_USER: admin
    DB_PASSWORD: yzXG2AtlLe
    DB_NAME: afp_ps

functions:

  getAllPatients:
    handler: src/handler_ospedale.getAllPatients
    events:
      - httpApi:
          path: /getAllPatients
          method: get
          cors: true
    
  getPatient:
    handler: src/handler_ospedale.getPatient
    events:
      - httpApi:
          path: /getPatient
          method: get
          cors: true

  createPatient:
    handler: src/handler_ospedale.createPatient
    events:
      - httpApi:
          path: /createPatient
          method: post
          cors: true

  updatePatient:
    handler: src/handler_ospedale.updatePatient
    events:
      - httpApi:
          path: /updatePatient/{id}
          method: put
          cors: true

  deletePatient:
    handler: src/handler_ospedale.deletePatient
    events:
      - httpApi:
          path: /deletePatient/{id}
          method: delete
          cors: true

  debugEvent:
    handler: src/handler_ospedale.debugEvent
    events:
      - httpApi:
          path: /debugEvent/{id}
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript