
service: serverless-2024-prova
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::730335289907:role/LabRole
  
  environment:
    DB_HOST: db-afp-2024.c7ky6o82a8hh.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_USER: admin
    DB_PASSWORD: yzXG2AtlLe
    DB_NAME: afp_ps

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  goodbye:
    handler: src/handler.goodbye
    events:
      - httpApi:
          path: /goodbye
          method: get
    
  getAllPatients:
    handler: src/handler.getAllPatients
    events:
      - httpApi:
          path: /getAllPatients
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript